name: handyman
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  circular_countdown_timer: 
  percent_indicator:
  firebase_core: 
  firebase_auth:
  firebase_messaging:
  firebase_storage:
  logger: 
  animated_splash_screen: 
  page_transition: 
  google_sign_in: 
  cloud_firestore: 
  random_string: 
  email_validator: 
  flutter_local_notifications: 
  shared_preferences: 
  get: 
  ionicons:
  carousel_slider: 
  video_player: 
  intl: 
  google_fonts: 
  http: 
  url_launcher: 
  permission_handler: 
  image_picker: 
  ffi: 
  meta: 
  json_annotation: 
  async: 
  chewie:
  expandable_text:
  flutter_rating_bar: 
  flutter_riverpod:
  flutter_hooks: 
  hooks_riverpod: 
  geocoding: 
  geolocator:
  lottie:
  crypto: 
  animated_text_kit:
  contacts_service:
  riverpod_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator:
  riverpod_lint:
flutter:
  uses-material-design: true

  assets:
        - assets/images/add.png
        - assets/images/applogo.png
        - assets/images/audioBooks.png
        - assets/images/classBasedCourse.png
        - assets/images/companylogo.png
        - assets/images/featuredcourses.png
        - assets/images/google.png
        - assets/images/placeholder_image.png
        - assets/images/rewards&refers.png
        - assets/lottie/lockanimation.json
        - assets/lottie/tandc.json
        - assets/lottie/animation1.json
        - assets/lottie/animation2.json
        - assets/lottie/animation3.json
        - assets/lottie/animation4.json
        - assets/images/infopic1.png
        - assets/images/infopic2.png
        - assets/images/infopic3.png
        - assets/images/infopic4.png
        - assets/images/plumbingRepairs.png
        - assets/images/electricalWork.png
        - assets/images/painting.png
        - assets/images/Carpentry.png
        - assets/images/applianceInstallation.png
        - assets/images/furnitureAssembly.png
        - assets/images/gardening.png
        - assets/images/generalMaintenance.png
        - assets/images/tilingFlooring.png
        - assets/images/hvacMaintenance.png
        - assets/images/roofingRepairs.png
        - assets/images/windowDoor.png
        - assets/images/interiorDesign.png
        - assets/images/pestControl.png
        - assets/images/cctvInstallation.png
        - assets/images/weldingMetalwork.png
        - assets/images/plasteringDrywall.png
        - assets/images/homeCleaning.png
        - assets/images/locksmith.png
        - assets/images/ceilingFan.png
        - assets/images/drainageMaintenance.png
        - assets/lottie/loading.json
        - assets/lottie/location.json
        - assets/images/logowhite.png
        - assets/images/logoblack.png
        - assets/lottie/locationforpayment.json
        - assets/lottie/confirmation.json
        - assets/lottie/waiting_for_confirmation.json
        - assets/lottie/no_orders_found.json
        - assets/lottie/error404.json
        - assets/lottie/refer.json
        - assets/lottie/thankyou.json





